#Call script to module: pickprops
#
############################################################# Set parameters
ignore=1
NoPartitions=80
savename_ext='_props-1'

###### Dictonary content for .yaml file
props_dict={'Generated by':'pickprops.get_props',
            'ignore':ignore} # Add your comments in same manner

############################################################## Define data
# Define folder of locs.hdf5 file
dir_names=[] 
dir_names.extend(['/fs/pool/pool-schwille-paint/Data/z.PAINT-checks/18-11-02_SDS-P1-9nt/SDS9nt-80_P1-20nM_p100mW-8deg_flat_1/18-11-02_FS/'])
# Define names of locs_picked.hdf5 file
file_names=[] 
file_names.extend(['SDS9nt-80_P1-20nM_p100mW-8deg_flat_1_MMStack.ome_locs_picked_d1-0.hdf5'])

#################################################### Load packages
import os #platform independent paths
import importlib
# Load user defined functions
import pickprops as props
import var_io as io
# Reload modules
importlib.reload(props)
importlib.reload(io)

############################################################# Read locs, apply props & save locs
######### Create list of paths
path=[os.path.join(dir_names[i],file_names[i]) for i in range(0,len(file_names))]

######### Read-Apply-Save loop
for p in path:
    ######### File read in
    locs,locs_yaml=io.read_locs(p)
    
    ######### Get number of frames
    NoFrames=locs_yaml[0]['Frames']
    
    ######### Apply non-parallelized props with progressbar 
#    locs_props=props.apply_props(locs,NoFrames,ignore)
    
    ######### Apply parallelized props (no progressbar)
    locs_props=props.apply_props_dask(locs,NoFrames,ignore,NoPartitions)
    
    ######### Save .hdf5 and .yaml of locs_props
    io.save_locs(locs_props,[locs_yaml,props_dict],p,savename_ext)
